run:
  skip-dirs:
    - vendor
    - .git
    - .idea
    - .github
    - var
linters:
  enable-all: true
  disable:
    - varcheck
    - exhaustruct
    - depguard
    - wsl
    - gci
    - nlreturn
    - scopelint
    - structcheck
    - nosnakecase
    - maligned
    - interfacer
    - ifshort
    - golint
    - exhaustivestruct
    - deadcode
linters-settings:
  varnamelen:
    min-len: 2
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - noctx
        - funlen
        - tparallel
        - paralleltest
    - path-except: _test\.go
      linters:
        - forbidigo
        - nilnil
  fix: true
