version: "2"
linters:
  default: all
  disable:
    - depguard
    - embeddedstructfieldcheck
    - exhaustruct
    - goconst
    - godox
    - gomodguard
    - gosec
    - lll
    - mnd
    - modernize
    - nilnesserr
    - nlreturn
    - noctx
    - noinlineerr
    - perfsprint
    - wsl
    - wsl_v5
  settings:
    varnamelen:
      min-name-length: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - gocyclo
          - gosec
          - noctx
          - paralleltest
          - tparallel
        path: _test\.go
      - linters:
          - forbidigo
          - nilnil
        path-except: _test\.go
    paths:
      - vendor
      - .git
      - .idea
      - .github
      - var
      - third_party$
      - builtin$
      - examples$
issues:
  fix: false
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - .git
      - .idea
      - .github
      - var
      - third_party$
      - builtin$
      - examples$
